language: node_js
node_js:
  - "8.1.3"
install:
  - npm install
script:
  - npm run build
after_success:
  - npm test
  - npm run lh -- https://ic-tech.ic-tech.now.sh
  - npm run lh -- https:/ic-tech.now.sh
